version: 2.1

workflows:
  hello-world-pipeline:
    jobs:
      - say-hello
      - hold_for_approval:
          type: approval
          requires:
            - say-hello
      - after-approval:
          requires:
            - hold_for_approval

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Hello World"

  after-approval:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "This runs only after manual approval!"
